version: '3.8'

services:
  eureka-server:
    build:
      context: ./Eureka-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"

  gateway:
    build:
      context: ./Gateway
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    depends_on:
      - eureka-server
    environment: 
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka-server:8761/eureka/


  service-calcul-polynomial:
    build:
      context: ./service-calcul-polynomial
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    depends_on:
      - eureka-server
      - database-calcul
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database-calcul:3306/service-calcul
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka-server:8761/eureka/

    command: /wait-for-it.sh database-calcul:3306 --timeout=60 --strict -- java -jar service-calcul-polynomial.jar

  service-historique:
    build:
      context: ./service-historique
      dockerfile: Dockerfile
    ports:
      - "8089:8089"
    depends_on:
      - eureka-server
      - database-historique
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database-historique:3306/service-historique
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka-server:8761/eureka/
    command: /wait-for-it.sh database-historique:3306 --timeout=60 --strict -- java -jar service-historique.jar

  service-user:
    build:
      context: ./service-user
      dockerfile: Dockerfile
    ports:
      - "8088:8088"
    depends_on:
      - eureka-server
      - database-user
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database-user:3306/service_user
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 
      SPRING_PROFILES_ACTIVE: dev
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka-server:8761/eureka/

    command: /wait-for-it.sh database-user:3306 --timeout=60 --strict && java -jar service-user.jar

  model-service:
    build:
      context: ./model
      dockerfile: Dockerfile
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"

  # Databases for each service
  database-calcul:
    image: mysql:5.7
    container_name: mysql-db-calcul
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: service-calcul
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "3307:3306"
    volumes:
      - mysql-data-calcul:/var/lib/mysql

  database-historique:
    image: mysql:5.7
    container_name: mysql-db-historique
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: service-historique
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "3308:3306"
    volumes:
      - mysql-data-historique:/var/lib/mysql

  database-user:
    image: mysql:5.7
    container_name: mysql-db-user
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: service_user
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "3309:3306"
    volumes:
      - mysql-data-user:/var/lib/mysql

volumes:
  mysql-data-calcul:
  mysql-data-historique:
  mysql-data-user:
