spring:
  cloud:
    gateway:
        routes:
          - id: r1
            uri: http://localhost:8088
            predicates:
              - Path=/users/**
          - id: r2
            uri: http://localhost:8089
            predicates:
              - Path=/calcule/**